# General bot configuration
bot:
  discord_key: ""
  command_prefix: ["!"]
  admin_minimum_role: "" #The lowest role that can use higher administrative functions, specify the exact name.
  guild: #Guild id
  extensions: [
    "cogs.dice",
    "cogs.currency",
    "cogs.echo",
    "cogs.show_image",
    "cogs.game_of_the_day.gotd",
    "cogs.stats",
    "cogs.gerber_renderer.render",
    "cogs.imgurAlbumHandler",
    "cogs.pinmanager",
    "cogs.api",
    "cogs.music"]

# Used by the show_image cog
show_image:
  cse_api_key: ""
  cse_cx: ""

currency:
  api_key: ""

pricechecker:
  api_token: ""

api:
  pinnedChannel: ""
  gitKey: ""
  gitRepo: ""

music:
  channel: #Voice channel for music
  commandChannel: #Text channel for music